version: "2.0"
   services:
     elasticsearch:
       image: elasticsearch:6.4.0
       container_name: elasticsearch
       ports:
         - "9200:9200"
         - "9300:9300"
 
   kibana:
      image: kibana:6.4.0
      container_name: kibana
      ports:
        - "5601:5601"
      links:
        - elasticsearch
 
    logstash:
      image: logstash:6.6.2
      container_name: logstash
      links:
        - elasticsearch
      volumes:
        - ./config-dir:/config-dir
      command: logstash -f /config-dir/logstash.conf
      depends_on:
        - elasticsearch
 
